app/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    IntegerField,
    PasswordField,
    SubmitField,
    BooleanField,
    StringField,
    TextAreaField,
    SelectField 
    
)

from wtforms.validators import (
    DataRequired,
    Length,
    Email,
    EqualTo,
    ValidationError,
    email_validator,
    NumberRange
)



class ComposeMailForm(FlaskForm):
    recipient_id = IntegerField('Recipient ID', validators=[DataRequired(), NumberRange(min=1100, max=8799)])
    subject = StringField("Subject", validators=[DataRequired()])
    priority = SelectField('Priority', choices=[('high', 'High'), ('average', 'Average'), ('low', 'Low')], validators=[DataRequired()])
    synopsys = StringField('Write a brief overview', validators=[DataRequired()])
    content = TextAreaField('Mail content...', validators=[DataRequired()])
    send = SubmitField('Send')
    draft = SubmitField('Draft')
    cancel = SubmitField('Cancel')
    

class UpdateMailForm(FlaskForm):
    close = SubmitField('Close')
    revert = SubmitField('Revert')
    archive = SubmitField('Archive')
    mark_read = SubmitField('Mark as read')
    

app/dashboard/__init__.py
# app/admin/__init__.py

from flask import Blueprint

dashboard = Blueprint('dashboard', __name__)

from . import views

app/dashboard/views.py
from flask import render_template, request, redirect, url_for, make_response, abort
from app import db
from flask_login import current_user, login_required
from . import dashboard
from ..models import VRecipients, VMailMaster, VMail, send_base_query, draft_base_query
from .forms import ComposeMailForm, UpdateMailForm
import datetime


@dashboard.route("/", methods=["GET", "POST"])
def homepage():
    return render_template("dashboard/dashboard_base.html")

@dashboard.route("/profile")
def profile():
    return render_template("dashboard/profile_blue.html", breadcrumb=['Profile'])

@dashboard.route("/inbox")
def inbox():
    if request.args.get('ref_id'):
        return redirect(url_for('inbox_mail', ref_id=request.args.get('ref_id')))
    
    inbox = send_base_query.filter(
        VMailMaster.recipient_id == current_user.id,  VMailMaster.hidden_to_recipient == False
    ).all()
    for i in inbox:
        print(i)
    headers = ['From', 'Subject', 'Preview', 'Status', 'Attachments', 'Data', 'Select']
    return render_template("dashboard/mailboxx.html", breadcrumb = ['Inbox'],headers=headers, mails=inbox, back_f='dashboard.inbox')


@dashboard.route("/inbox/mail/<int:ref_id>", methods=["GET", "POST"])
def inbox_mail(ref_id):
    inbox_mail = db.session.query(VMailMaster).get_or_404(ref_id)
    if inbox_mail.recipient_id != current_user.id:
        abort(403)
    form = UpdateMailForm()
    if form.validate_on_submit(): 
        if form.mark_read.data:
            inbox_mail.recipient_read = True
            inbox_mail.mail_opened_time = datetime.datetime.now().time()
            inbox_mail.mail_opened_date = datetime.now().date()
        elif form.revert.data:
            inbox_mail.hidden_to_recipient = False
        elif form.archive.data:
            inbox_mail.hidden_to_recipient = True
        db.session.commit()
        return redirect(url_for("dashboard.homepage"))
    return render_template("dashboard/mail.html", mail=inbox_mail)


@dashboard.route("/inbox/sentmail/<int:ref_id>")
def sendbox_mail(ref_id):
    sent_mail = db.session.query(VMailMaster).get_or_404(ref_id)
    if sent_mail.author_prsnl_id != current_user.id:
        abort(403)
    return render_template("dashboard/mail.html", mail=sent_mail) 
    

@dashboard.route("/archive")
def archive():
    archive = send_base_query.filter(
        VMailMaster.recipient_id == current_user.id, VMailMaster.hidden_to_recipient == True
    ).all()
    # return render_template("test-list.html", func_name="archive", items=archive)
    headers = ['To', 'Subject', 'Preview', 'Status', 'Attachments', 'Data', 'Select']
    return render_template("dashboard/mailboxx.html", breadcrumb = ['Archive'], headers=headers, mails=archive)



@dashboard.route("/sendbox/")
@login_required
def sendbox():
    sendbox = send_base_query.filter_by(author_prsnl_id= current_user.id).all()
    headers = ['To', 'Subject', 'Preview', 'Status', 'Attachments', 'Data', 'Select']
    return render_template("dashboard/mailboxx.html", breadcrumb = ['Sendbox'], headers=headers, mails=sendbox)



@dashboard.route("/drafts/")
@login_required
def drafts():
    drafts = draft_base_query.filter_by(author_prsnl_id=current_user.id).all()
    headers = ['To', 'Subject', 'Preview', 'Attachments', 'Data', 'Select']
    return render_template("dashboard/mailboxx.html", breadcrumb = ['Drafts'], headers=headers, mails=drafts)


@dashboard.route("/new_mail", methods=["GET", "POST"])
def compose():
    form = ComposeMailForm()
    if form.validate_on_submit():
        mail = VMail(ml_priority = form.priority.data,
                    ml_sender = current_user.id,
                    ml_subject = form.subject.data,
                    ml_synopsis = form.synopsys.data,
                    ml_content = form.content.data,
                    ml_status = form.send.data
        )
        
        db.session.add(mail)
        db.session.flush()
        
        #TODO count recipients with helper func
        recipient = VRecipients(ml_id = mail.ml_id, 
                                  recipient_id = form.recipient_id.data
                                  )
        
        db.session.add(recipient)
        db.session.commit()

        return redirect(url_for('dashboard.sendbox'))
    return render_template("dashboard/compose.html", form=form, mail_type='New Mail')


@dashboard.route("/drafts/edit/<int:ref_id>/<int:ml_id>", methods=["GET", "POST"])
@login_required
def edit_draft(ref_id, ml_id):
   
    # draft = draft_base_query.filter(VMail.ml_id == ml_id ).first()
    draft = db.session.query(VMail).filter(VMail.ml_id == ml_id).first()
    if draft.ml_sender != current_user.id:
        abort(403)
    form = ComposeMailForm()
    edited = VMail()
    if request.method =='POST':
        if form.validate_on_submit():
            if form.send.data:
                draft.ml_status = True
            elif form.cancel.data:
                draft.delete()
            db.session.commit()
            print('successfully')
            return redirect(url_for("dashboard.homepage"))
    elif request.method == "GET":
        # form.recipient_id.data = draft.recipient_id
        form.subject.data = draft.ml_subject
        form.priority.data = draft.ml_priority
        form.synopsys.data = draft.ml_synopsis
        form.content.data = draft.ml_content
    return render_template("dashboard/compose.html", form=form, mail_type='Draft')


@dashboard.route('/open/')
def open_mail():
    mail_type  = request.args.get('mail_type')
    ref_id = request.args.get('ref_id')
    ml_id = request.args.get('ml_id')

    if mail_type == 'Drafts':
        return redirect (url_for('dashboard.edit_draft', ref_id=ref_id, ml_id=ml_id))
    elif mail_type == 'Sendbox':
        return redirect(url_for('dashboard.sendbox_mail', ref_id=ref_id))
    else:
        return redirect(url_for('dashboard.inbox_mail', ref_id=ref_id))

app/templates/dashboard/compose.html
{% import 'macros.html' as macros %} {% extends "dashboard/dashboard_base.html" %} {%
block title %}new draft{% endblock %} 
{% block stylesheets %}
<script src="https://use.fontawesome.com/55ae3698a0.js"></script>
{% endblock stylesheets %}

{% block header_title %}
{{ mail_type }}
{% endblock header_title %}

{% block header_btn %}
{% endblock header_btn %}


{% block page_table %}

<div class="row row-card-no-pd">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <div class="card-head-row card-tools-still-right">
          <h4 class="card-title">Compose a new mail</h4>

        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-12 .col-sm-6 .col-lg-8">
            <form method="POST" action="">
             
              {{ form.hidden_tag() }}

              <!---recipient id      subject      priority-->
              <div class="form-row">
               {% if mail_type != 'Draft' %}
                  {{ macros.render_floating_form_gp(form.recipient_id) }}
               {% endif %} 
                <div class="col">
                  {{ macros.render_floating_form_gp(form.subject) }}
                </div>
                <div class="col">
                  <div class="form-group form-floating-label">
                    {{ form.priority(class="form-control input-border-bottom")
                    }}
                  </div>
                </div>
              </div>

              <!--synopsis-->
              <div class="form-group row">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">Synopsis</span>
                  </div>
                  {% if form.synopsys.errors %} {{ form.synopsys("form-control
                  is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                  {% else %} {{ form.synopsys(class="form-control") }} {% endif
                  %}
                </div>
              </div>
                  {% if form.content.errors %}
                      {{ form.content(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                          {% for error in form.content.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ form.content(class="form-control" , rows="10") }}
                  {% endif %}
                </div>
              
              
                <!--attachment-->
              <div class="form-group">
                <div class="demo-icon">
                   <div class="icon-preview">
                     <i class="la flaticon-tool"></i>
                    </div> 
                    <div class="icon-class">
                      <input
                        type="file"
                        class="form-control-file"
                        id="exampleFormControlFile1"
                      />
                    </div>
                   </div>

              </div>

              
              <div class="form-group">
                
                
                <p class="demo">
                 
                  {{ form.cancel(class="btn btn-default") }}
                  
                  {% if mail_type == 'New Mail' %}
                  {{ form.draft(class="btn btn-secondary") }}
                   {% endif %}

                  {{ form.send(class="btn btn-primary") }}
                </p>

                </div>
                
              </div>


            </form>
          </div>
          <!-- <div class="col-md-6"> --->
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock page_table %}

app/templates/dashboard/dashboard_base.html
{% extends "layouts/base.html" %} {% block title %}{% endblock title %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}
 {% block content %}

<div class="content">
  <div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
      <div
        class="d-flex align-items-left align-items-md-center flex-column flex-md-row"
      >
        <!---insert header data (if any) in sub classes-->
        <div>
          <h2 class="text-white pb-2 fw-bold">
            {% block header_title %} {% endblock header_title %}
          </h2>

          <h5 class="text-white op-7 mb-2">
            {% block header_sub %} {% endblock header_sub %}
          </h5>
        </div>

        <div class="ml-md-auto py-2 py-md-0">
          {% block header_btn %}
          <!--insert a relative action button here-->
          <a href="#" class="btn btn-white btn-border btn-round mr-2">compose</a>
          <a href="#" class="btn btn-secondary btn-round">settings</a>
          {% endblock header_btn %}
        </div>
      </div>
    </div>
  </div>
  <div class="page-inner mt--5">
    <!-- <div class="row mt--2"> -->
      
    {% block page_table %} {% endblock page_table %}
    <!-- </div> -->
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script>
  Circles.create({
    id: "circles-1",
    radius: 45,
    value: 60,
    maxValue: 100,
    width: 7,
    text: 5,
    colors: ["#f1f1f1", "#FF9E27"],
    duration: 400,
    wrpClass: "circles-wrp",
    textClass: "circles-text",
    styleWrapper: true,
    styleText: true,
  });

  Circles.create({
    id: "circles-2",
    radius: 45,
    value: 70,
    maxValue: 100,
    width: 7,
    text: 36,
    colors: ["#f1f1f1", "#2BB930"],
    duration: 400,
    wrpClass: "circles-wrp",
    textClass: "circles-text",
    styleWrapper: true,
    styleText: true,
  });

  Circles.create({
    id: "circles-3",
    radius: 45,
    value: 40,
    maxValue: 100,
    width: 7,
    text: 12,
    colors: ["#f1f1f1", "#F25961"],
    duration: 400,
    wrpClass: "circles-wrp",
    textClass: "circles-text",
    styleWrapper: true,
    styleText: true,
  });

  var totalIncomeChart = document
    .getElementById("totalIncomeChart")
    .getContext("2d");

  var mytotalIncomeChart = new Chart(totalIncomeChart, {
    type: "bar",
    data: {
      labels: ["S", "M", "T", "W", "T", "F", "S", "S", "M", "T"],
      datasets: [
        {
          label: "Total Income",
          backgroundColor: "#ff9e27",
          borderColor: "rgb(23, 125, 255)",
          data: [6, 4, 9, 5, 4, 6, 4, 3, 8, 10],
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      legend: {
        display: false,
      },
      scales: {
        yAxes: [
          {
            ticks: {
              display: false, //this will remove only the label
            },
            gridLines: {
              drawBorder: false,
              display: false,
            },
          },
        ],
        xAxes: [
          {
            gridLines: {
              drawBorder: false,
              display: false,
            },
          },
        ],
      },
    },
  });

  $("#lineChart").sparkline([105, 103, 123, 100, 95, 105, 115], {
    type: "line",
    height: "70",
    width: "100%",
    lineWidth: "2",
    lineColor: "#ffa534",
    fillColor: "rgba(255, 165, 52, .14)",
  });
</script>

{% endblock javascripts %}

app/templates/dashboard/drafts.html
{% extends 'dashboard_base.html' %} 
{% block title %}{% endblock %}

{% block header_title %} 
{% endblock header_title %} 
{% block header_btn %}
{% endblock header_btn %}
{% block header_sub %}{% endblock header_sub %}
{% block page_table %}
<div class="row mt--2">
<div class="col-12">
  <div class="card">
    <!-- <div class="card-header"> -->
    <!-- <div class="card-title">My Contacts</div> -->
    <!-- </div> -->
    <div class="card-body">
      <!-- <div class="card-title fw-mediumbold">Inbox</div> -->
      <table class="table table-head-bg-primary mt-4" class="table-responsive">
        <thead>
          <tr>
            <th scope="col">To</th>
            <th scope="col">Subject</th>
            <th scope="col">Preview</th>
            <th scope="col" class="text-center">Date</th>
            <th scope="col" class="text-center">Action</th>
            <th scope="col" class="text-center">Attachment</th>
          </tr>
        </thead>
        <tbody>
          {% for draft in drafts %}
          <tr>
            <td>{{ draft.prsnl_name }}</td>
            <td>{{ draft.prsnl_last_name }}</td>
            <td>{{ draft.prsnl_email }}</td>
            <td colspan="2">
              <a
                href="{{ url_for('dashboard.homepage') }}"
                class="btn btn-icon btn-round btn-info"
              >
                <i class="fa fa-info"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

  {% endblock page_table %}</div>

app/templates/dashboard/inbox.html
{% extends 'dashboard/dashboard_base.html' %} 
{% block title %}Inbox{% endblock title%}

{% block header_title %}
 Inbox 
{% endblock header_title %} 
{% block header_btn %}
{% endblock header_btn %}
{% block header_sub %}  {% endblock header_sub %}
{% block page_table %}
<div class="row mt--2">
  <!--if favorite is move to another page moke inbox col-md12 else col-12Inbox col-md-8-->
<div class="col-12">
  <div class="card">
    <!-- <div class="card-header"> -->
    <!-- <div class="card-title">My Contacts</div> -->
    <!-- </div> -->
    <div class="card-body">
      <!-- <div class="card-title fw-mediumbold">Inbox</div> -->
      <table class="table table-head-bg-primary col-md-12 table-responsive">
        <thead>
          <tr>
            <th scope="col">From</th>
            <th scope="col">Subject</th>
            <th scope="col">Preview</th>
            <th scope="col" class="text-center"> Status </th>
            <th scope="col" colspan="2" class="text-center">Attachment</th>
            <th scope="col" colspan="2" class="text-center">Date</th>
            <th scope="col" colspan="2" class="text-center">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for mail in inbox %}
          <tr>
            <td colspan="2">{{ mail.recipient_name }} {{ mail.recipient_last_name}}</td>
            <td >{{ mail.mail_subject }}</td>
            <td >{{ mail.mail_synopsys }}</td>
            <td colspan="2">{{ mail.recipient_read }}</td>
            <td>   
                {% if mail.mail_attachments %}
                    yes
                {% else %}
                    no            
                {% endif %}
          </td>
            <td colspan="2">{{ mail.mail_composed_date }}</td>
            <td colspan="2">

              <button class="btn btn-primary btn-border btn-round"> view </button>

            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<!---most frequent--->
<!-- <div class="col-md-4 ml-auto">
  <div class="card card-round">
    <div class="card-body">
      <div class="card-title fw-mediumbold">Suggested People</div>
      <div class="card-list">
        {% for contact in contacts %}
        <div class="item-list">
          <div class="avatar">
            <img
              src="/static/assets/img/talha.jpg"
              alt="..."
              class="avatar-img rounded-circle"
            />
          </div>
          <div class="info-user ml-3">
            <div class="Name">{{ contact.name }}</div>
            <div class="Post title">{{ contact.post_title}}</div>
          </div>
          <button class="btn btn-icon btn-primary btn-round btn-xs">
            <i class="fa fa-plus"></i>
          </button>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div> -->
</div>  
{% endblock page_table %}</div>

app/templates/dashboard/mailboxx.html
{% extends "layouts/base.html" %}

{% block title %} Mailbox{% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<div class="content">
<div class="page-inner">
<div class="page-header">
    <h4 class="page-title">{{ breadcrumb[0] }}</h4>
    <ul class="breadcrumbs">
        <li class="nav-home">
            <a href="#">
                <i class="flaticon-home"></i>
            </a>
        </li>
        <li class="separator">
            <i class="flaticon-right-arrow"></i>
        </li>
        <li class="nav-item">
            <a href="#">{{ breadcrumb[0] }}</a>
        </li>
        <li class="separator">
            <i class="flaticon-right-arrow"></i>
        </li>
        <li class="nav-item">
            <a href="#">{{ breadcrumb[1] }}</a>
        </li>
    </ul>
</div>
<!--table-->
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">View {{ breadcrumb[0]}}</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="basic-datatables" class="display table table-striped table-hover" >
                    <thead>
                        <tr>
                 

                            {% for header in headers %}
                                <th>{{ header}}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            {% for header in headers %}
                                <th>{{ header}}</th>
                            {% endfor %}
                        </tr>
                    </tfoot>
                    <tbody>
                        
                           
                            {%for mail in mails %}
                            <tr>    {% if breadcrumb[0] == 'Inbox' %}
                                    <td> {{ mail.author_name }} {{ mail.author_last_name }}</td> 
                                    {% else %}
                                      <td>    {{ mail.recipient_name }} {{ mail.recipient_last_name }} </td> 
                                    {% endif %}}

                                   <td >{{ mail.mail_subject }}</td>
                                   <td >{{ mail.mail_synopsys }}</td>
                                   <td >
                                    {% if  not mail.recipient_read %}
                                        <i class="far fa-envelope"></i>
                                    {% else %}
                                    <i class="far fa-envelope-open"></i>
                                    {% endif %}
                                    </td>
                                    <td> 
                                        {% if mail.mail_attachments %}
                                        <button type="button" class="btn btn-icon btn-link">
                                                 <i class="fa fa-link"></i>
                                        </button>
                                        {% else %}
                                        <button type="button" class="btn btn-icon btn-link" disabled="disabled">
                                            <i class="fa fa-link"></i>
                                   </button>
                                        {% endif %}
                                    </td>
                                    <td> {{ mail.mail_composed_date }}</td>
                                    <td>
                                        
                                            <a href="{{ url_for('dashboard.open_mail' , ref_id=mail.reference_id, ml_id=mail.mail_id, mail_type=breadcrumb[0]) }}"
                                            <button class="btn btn-primary btn-round">Open</button>
                                      
                                      
                                      
                                    </td>
                                </tr>
                            {% endfor %}
                        
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

app/templates/dashboard/profile.html
{% extends "layouts/base.html" %}

{% block title %} Profile {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
			
    <div class="row">
        <div class="col-md-8">
        <div class="card">
            <div class="card-header card-header-primary">
            <h4 class="card-title">Edit Profile</h4>
            <p class="card-category">Complete your profile</p>
            </div>
            <div class="card-body">
            <form>
                <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                    <label class="bmd-label-floating">UserID (disabled)</label>
                    <input type="text" class="form-control" disabled value="{{ current_user.id }}">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                    <label class="bmd-label-floating">Username</label>
                    <input type="text" class="form-control" value="{{ current_user.username }}">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                    <label class="bmd-label-floating">Email address</label>
                    <input type="email" class="form-control" value="{{ current_user.email }}">
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                    <label class="bmd-label-floating">Fist Name</label>
                    <input type="text" class="form-control">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                    <label class="bmd-label-floating">Last Name</label>
                    <input type="text" class="form-control">
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                    <label class="bmd-label-floating">Adress</label>
                    <input type="text" class="form-control">
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                    <label class="bmd-label-floating">City</label>
                    <input type="text" class="form-control">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                    <label class="bmd-label-floating">Country</label>
                    <input type="text" class="form-control">
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                    <label class="bmd-label-floating">Postal Code</label>
                    <input type="text" class="form-control">
                    </div>
                </div>
                </div>
                <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                    <label>About Me</label>
                    <div class="form-group">
                        <label class="bmd-label-floating"> Lamborghini Mercy, Your chick she so thirsty, I'm in that two seat Lambo.</label>
                        <textarea class="form-control" rows="5"></textarea>
                    </div>
                    </div>
                </div>
                </div>
                <button type="submit" class="btn btn-primary pull-right">Update Profile</button>
                <div class="clearfix"></div>
            </form>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card card-profile">
            <div class="card-avatar">
            <a href="#pablo">
                <img class="img" src="/static/assets/img/faces/marc.jpg" />
            </a>
            </div>
            <div class="card-body">
            <h6 class="card-category text-gray">
                {{ current_user.username }}
            </h6>
            <h4 class="card-title">
                {{ current_user.email }}
            </h4>
            <p class="card-description">
                Don't be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
            </p>
            <a href="#pablo" class="btn btn-primary btn-round">Follow</a>
            </div>
        </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

	<!-- Atlantis DEMO methods, don't include it in your project! -->
	<script src="/static/assets/js/setting-demo.js"></script>
	<script src="/static/assets/js/demo.js"></script>

	<script>
		Circles.create({
			id:'circles-1',
			radius:45,
			value:60,
			maxValue:100,
			width:7,
			text: 5,
			colors:['#f1f1f1', '#FF9E27'],
			duration:400,
			wrpClass:'circles-wrp',
			textClass:'circles-text',
			styleWrapper:true,
			styleText:true
		})

		Circles.create({
			id:'circles-2',
			radius:45,
			value:70,
			maxValue:100,
			width:7,
			text: 36,
			colors:['#f1f1f1', '#2BB930'],
			duration:400,
			wrpClass:'circles-wrp',
			textClass:'circles-text',
			styleWrapper:true,
			styleText:true
		})

		Circles.create({
			id:'circles-3',
			radius:45,
			value:40,
			maxValue:100,
			width:7,
			text: 12,
			colors:['#f1f1f1', '#F25961'],
			duration:400,
			wrpClass:'circles-wrp',
			textClass:'circles-text',
			styleWrapper:true,
			styleText:true
		})

		var totalIncomeChart = document.getElementById('totalIncomeChart').getContext('2d');

		var mytotalIncomeChart = new Chart(totalIncomeChart, {
			type: 'bar',
			data: {
				labels: ["S", "M", "T", "W", "T", "F", "S", "S", "M", "T"],
				datasets : [{
					label: "Total Income",
					backgroundColor: '#ff9e27',
					borderColor: 'rgb(23, 125, 255)',
					data: [6, 4, 9, 5, 4, 6, 4, 3, 8, 10],
				}],
			},
			options: {
				responsive: true,
				maintainAspectRatio: false,
				legend: {
					display: false,
				},
				scales: {
					yAxes: [{
						ticks: {
							display: false //this will remove only the label
						},
						gridLines : {
							drawBorder: false,
							display : false
						}
					}],
					xAxes : [ {
						gridLines : {
							drawBorder: false,
							display : false
						}
					}]
				},
			}
		});

		$('#lineChart').sparkline([105,103,123,100,95,105,115], {
			type: 'line',
			height: '70',
			width: '100%',
			lineWidth: '2',
			lineColor: '#ffa534',
			fillColor: 'rgba(255, 165, 52, .14)'
		});
	</script>

{% endblock javascripts %}